# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# Pipeline that checks branches that have been pushed to "Main" OR are the source branch in a newly created pull request into "Main"
# Fails the test if there are Python syntax errors or undefined names OR pytest fails

name: Pydicer Pytest and Pylint Validaiton

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, 3.10]
        poetry-version: [1.1.12]
        # os: [ubuntu-20.04, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install Python modules with poetry
        # Install numpy first so that pyradiomics can compile
        # TODO remove this once https://github.com/AIM-Harvard/pyradiomics/pull/761 lands
        run: |
          poetry run pip install --upgrade pip
          pip install numpy
          poetry install
      - name: Lint with Pylint
        run: |
          poetry run pylint pydicer
      - name: Pytest validation
        run: |
          poetry run pytest
